module.exports = [
	["Web Technologies", 20],
      
	["HTML5", 15],
	["CSS3", 15],
	["ECMA ", 15],
	["Flutter", 10],
	["Nodejs", 10],
	["NestJs", 10],
	["<Canvas>", 10],
	["JSON", 10],
	["React", 10],
	["Vue", 10],
	["Webpack", 10],
	["NPM", 10],
	["SVG", 10],
	["animation", 10],
	["Performance", 10],
	["Browser", 10],
	["Rollup", 10],
	["Monitor", 10],
	["Web Storage", 10],
	["Promise", 10],
	["async/await", 10],
	["MSE", 10],
	["PWA", 10],
	["Web Worker", 10],
	["Web Service", 10],
	["IndexDB", 10],
	["Web3.0", 10],
	["Dart", 10],
	["calc()", 5],
	["supports()", 5],
	["media queries", 5],
	["full screen", 5],
	["notification", 5],
	["orientation", 5],
	["requestAnimationFrame", 5],
	["border-radius", 5],
	["box-sizing", 5],
	["rgba()", 5],
	["text-shadow", 5],
	["box-shadow", 5],
	["flexbox", 5],
	["viewpoint", 5]
      
      
      
	// ["HTML",10],
	// ["<canvas>",10],
	// ["CSS",10],
	// ["JavaScript",10],
	// ["Document Object Model",10],
	// ["<audio>",10],
	// ["<video>",10],
	// ["Web Workers",10],
	// ["XMLHttpRequest",10],
	// ["SVG",10],
	// ["JSON.parse()",10],
	// ["Geolocation",10],
	// ["data attribute",10],
	// ["transform",10],
	// ["transition",10],
	// ["animation",10],
	// ["setTimeout",10],
	// ["@font-face",10],
	// ["Typed Arrays",10],
	// ["FileReader API",10],
	// ["FormData",10],
	// ["IndexedDB",10],
	// ["getUserMedia()",10],
	// ["postMassage()",10],
	// ["CORS",10],
	// ["strict mode",10],
	// ["calc()",10],
	// ["supports()",10],
	// ["media queries",10],
	// ["full screen",10],
	// ["notification",10],
	// ["orientation",10],
	// ["requestAnimationFrame",10],
	// ["border-radius",10],
	// ["box-sizing",10],
	// ["rgba()",10],
	// ["text-shadow",10],
	// ["box-shadow",10],
	// ["flexbox",10],
	// ["viewpoint",10]
];